## Embeddings

In [1]:
from arcgis.learn import Embeddings 

### Embeddings for images

In [2]:
emb_image = Embeddings('image')

#### Get supported backbones

In [3]:
emb_image.supported_backbones('image')

['resnet18',
 'resnet34',
 'resnet50',
 'resnet101',
 'resnet152',
 'densenet121',
 'densenet169',
 'densenet161',
 'densenet201',
 'vgg11',
 'vgg11_bn',
 'vgg13',
 'vgg13_bn',
 'vgg16',
 'vgg16_bn',
 'vgg19',
 'vgg19_bn',
 'mobilenet_v2']

#### Get embeddings

In [4]:
ret_emb = emb_image.get(r"C:\Users\Neha Sharma\Downloads\certi\trial", return_embeddings= True, show_progress=True) #folder path containing images
ret_emb

array([[0.044067, 0.014703, 0.016471, 0.068207, ..., 0.02441 , 0.019436, 0.008121, 0.013543]])

#### Get normalized embeddings

In [5]:
ret_emb = emb_image.get(r"C:\Users\Neha Sharma\Downloads\certi\trial", return_embeddings= True, normalize=True) #folder path containing images
ret_emb

array([[0.044067, 0.014703, 0.016471, 0.068207, ..., 0.02441 , 0.019436, 0.008121, 0.013543]])

#### Save embeddings as .h5 file (embeddings folder should be present at the notebook location)

In [6]:
emb_image.get(r"C:\Users\Neha Sharma\Downloads\certi\trial", return_embeddings= False)

'C:\\Users\\Neha Sharma\\Downloads\\certi\\arcgis-python-api\\samples\\04_gis_analysts_data_scientists\\certification\\embeddings\\embeddings_2025-03-27_14-07-06.h5'

#### Load saved embeddings

In [7]:
emb_image_load = Embeddings('image')
load = emb_image_load.load(r'C:\\Users\\Neha Sharma\\Downloads\\certi\\arcgis-python-api\\samples\\04_gis_analysts_data_scientists\\certification\\embeddings\\embeddings_2025-03-27_12-21-24.h5')
load

(array([[0.044067, 0.014703, 0.016471, 0.068207, ..., 0.02441 , 0.019436, 0.008121, 0.013543]]),
 array([b'C:\\Users\\Neha Sharma\\Downloads\\certi\\trial\\6135838727f4170005130771.tif'], dtype=object))

In [8]:
emb_image.visualize(r'C:\\Users\\Neha Sharma\\Downloads\\certi\\arcgis-python-api\\samples\\04_gis_analysts_data_scientists\\certification\\embeddings\\embeddings_2025-03-27_12-21-24.h5',
                    n_clusters = 5,
                    dimensions=2
                    )

ValueError: n_components=2 must be between 0 and min(n_samples, n_features)=1 with svd_solver='full'

### Embeddings in Text

In [9]:
emb_text = Embeddings('text', backbone = 'distilbert-base-nli-stsb-mean-tokens')

Exception: Wrong backbone - distilbert-base-nli-stsb-mean-tokens choosen for dataset-type - text. Kindly call the `Embeddings.supported_backbones('text')` to see the supported backbones for - text dataset-type.

In [12]:
Embeddings.supported_backbones('text')

['sentence-transformers/distilbert-base-nli-stsb-mean-tokens',
 'sentence-transformers/bert-base-nli-max-tokens',
 'sentence-transformers/bert-base-nli-cls-token',
 'See all `TextEmbedding` models at https://huggingface.co/sentence-transformers']

In [13]:
Embeddings.supported_backbones('image')

['resnet18',
 'resnet34',
 'resnet50',
 'resnet101',
 'resnet152',
 'densenet121',
 'densenet169',
 'densenet161',
 'densenet201',
 'vgg11',
 'vgg11_bn',
 'vgg13',
 'vgg13_bn',
 'vgg16',
 'vgg16_bn',
 'vgg19',
 'vgg19_bn',
 'mobilenet_v2']